"""phase 1.5 widened schema

Revision ID: 09ebec4df48c
Revises: 
Create Date: 2026-05-29 06:05:03.735053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 -- autogenerate emits sqlmodel.sql.sqltypes.* (e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = '09ebec4df48c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('schedules', sa.JSON(), nullable=False),
    sa.Column('memory', sa.JSON(), nullable=False),
    sa.Column('interaction_rules', sa.JSON(), nullable=False),
    sa.Column('guardrails', sa.JSON(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_node_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='runstatus'), nullable=False),
    sa.Column('input', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_nodes',
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('node_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_type', sa.Enum('agent', 'supervisor', 'tool', name='nodetype'), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'node_key', name='uq_workflow_node_key')
    )
    with op.batch_alter_table('workflow_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_nodes_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('messages',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('system', 'user', 'assistant', 'tool', name='messagerole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('source_node_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_node_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direction', sa.Enum('internal', 'inbound', 'outbound', name='messagedirection'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'delivered', 'failed', name='messagestatus'), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_run_id'), ['run_id'], unique=False)

    op.create_table('run_events',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('step_start', 'step_end', 'llm_chunk', 'tool_call', 'error', 'run_complete', name='runeventtype'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_events_run_id'), ['run_id'], unique=False)

    op.create_table('workflow_edges',
    sa.Column('source_node_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_node_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id', 'source_node_key'], ['workflow_nodes.workflow_id', 'workflow_nodes.node_key'], name='fk_edge_source_node', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id', 'target_node_key'], ['workflow_nodes.workflow_id', 'workflow_nodes.node_key'], name='fk_edge_target_node', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_edges_workflow_id'), ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_edges_workflow_id'))

    op.drop_table('workflow_edges')
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_events_run_id'))

    op.drop_table('run_events')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_run_id'))
        batch_op.drop_index(batch_op.f('ix_messages_agent_id'))

    op.drop_table('messages')
    with op.batch_alter_table('workflow_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_nodes_workflow_id'))

    op.drop_table('workflow_nodes')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_workflow_id'))

    op.drop_table('runs')
    op.drop_table('workflows')
    op.drop_table('agents')
    # ### end Alembic commands ###
