"""phase 5 channel_sessions

Revision ID: d455a9785e29
Revises: 85f81e483b12
Create Date: 2026-05-30 09:22:38.763070

Adds `channel_sessions`: maps an external chat (Telegram) to the workflow it talks to.
Chat->workflow routing is runtime state (set via the bot's /use command), so it lives
in its own table rather than in an agent's `channels` config. FKs are SET NULL so
deleting a workflow/run/agent clears the binding instead of cascading.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401 -- autogenerate emits sqlmodel.sql.sqltypes.* (e.g. AutoString)


# revision identifiers, used by Alembic.
revision: str = 'd455a9785e29'
down_revision: Union[str, None] = '85f81e483b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_chat_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_chat_id', name='uq_channel_session')
    )
    with op.batch_alter_table('channel_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_sessions_external_chat_id'), ['external_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_sessions_provider'), ['provider'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_sessions_provider'))
        batch_op.drop_index(batch_op.f('ix_channel_sessions_external_chat_id'))

    op.drop_table('channel_sessions')
    # ### end Alembic commands ###
